//
//  EventMonitor.swift
//  Flipio
//
//  Monitors keyboard and mouse events globally to detect Option key taps
//  and track typed words for layout conversion using CGEventSupervisor.
//

import AppKit
import ApplicationServices
import CGEventSupervisor
import os

/// Monitors for Option key tap and maintains a typed-word buffer for conversion.
final class EventMonitor {
    private let shortcutKeyDetector = OptionTapDetector()
    private let wordBuffer = TypedWordBuffer()
    private lazy var coordinator = TextConversionService(typedWordBuffer: wordBuffer)
    static let shared = EventMonitor()
    private let subscriberID = "FlipioEventMonitor"
    
    func start() {
        FlipioApp.logger.info("Starting event monitor with CGEventSupervisor")
        
        CGEventSupervisor.shared.subscribe(
            as: subscriberID,
            to: .cgEvents(
                .flagsChanged,
                .keyDown,
                .leftMouseDown,
                .rightMouseDown,
                .otherMouseDown
            ),
            using: { [weak self] event in
                self?.handleEvent(event)
            }
        )
    }
    
    func stop() {
        FlipioApp.logger.info("Stopping event monitor")
        CGEventSupervisor.shared.cancel(subscriber: subscriberID)
    }
    
    private func handleEvent(_ event: CGEvent) {
        let type = event.type
        let typeDescription = eventTypeDescription(type)
        let flagsDescription = eventFlagsDescription(event.flags)
        let keyInfo = keyDescription(for: event, type: type)
        
        FlipioApp.logger.debug("handleEvent: type=\(typeDescription), flags=\(flagsDescription)\(keyInfo)")
        
        // Ignore synthetic events generated by Flipio to avoid corrupting the Option key detector state
        if event.getIntegerValueField(.eventSourceUserData) == FlipioSyntheticEventUserData {
            FlipioApp.logger.debug("own event detected, ignoring. TODO: never happens but should")
            return
        }
        
        switch type {
        case .flagsChanged:
            let shouldConvert = shortcutKeyDetector.isShortcutTriggered(newFlags: event.flags)
            if shouldConvert {
                stop()
                coordinator.convert()
                //resubscribe because subscription is cancelled after handling an event for some reason
                start()
                return
            }
            
        case .keyDown, .leftMouseDown, .rightMouseDown, .otherMouseDown:
            wordBuffer.update(with: event, type: type)
            shortcutKeyDetector.reset()
            
        default:
            FlipioApp.logger.debug("event type=\(type.rawValue) (unhandled)")
        }
    }
    
    private func eventTypeDescription(_ type: CGEventType) -> String {
        switch type {
        case .null: return "null"
        case .leftMouseDown: return "leftMouseDown"
        case .leftMouseUp: return "leftMouseUp"
        case .rightMouseDown: return "rightMouseDown"
        case .rightMouseUp: return "rightMouseUp"
        case .mouseMoved: return "mouseMoved"
        case .leftMouseDragged: return "leftMouseDragged"
        case .rightMouseDragged: return "rightMouseDragged"
        case .keyDown: return "keyDown"
        case .keyUp: return "keyUp"
        case .flagsChanged: return "flagsChanged"
        case .scrollWheel: return "scrollWheel"
        case .tabletPointer: return "tabletPointer"
        case .tabletProximity: return "tabletProximity"
        case .otherMouseDown: return "otherMouseDown"
        case .otherMouseUp: return "otherMouseUp"
        case .otherMouseDragged: return "otherMouseDragged"
        default: return "unknown(\(type.rawValue))"
        }
    }
    
    private func eventFlagsDescription(_ flags: CGEventFlags) -> String {
        var components: [String] = []
        
        if flags.contains(.maskAlphaShift) { components.append("CapsLock") }
        if flags.contains(.maskShift) { components.append("Shift") }
        if flags.contains(.maskControl) { components.append("Control") }
        if flags.contains(.maskAlternate) { components.append("Option") }
        if flags.contains(.maskCommand) { components.append("Command") }
        if flags.contains(.maskNumericPad) { components.append("NumPad") }
        if flags.contains(.maskHelp) { components.append("Help") }
        if flags.contains(.maskSecondaryFn) { components.append("Fn") }
        
        if components.isEmpty {
            return "none"
        }
        return components.joined(separator: "+")
    }
    
    private func keyDescription(for event: CGEvent, type: CGEventType) -> String {
        guard type == .keyDown || type == .keyUp else {
            return ""
        }
        
        let keyCode = event.getIntegerValueField(.keyboardEventKeycode)
        var result = ", keyCode=\(keyCode)"
        
        // Get the characters from the event
        if let nsEvent = NSEvent(cgEvent: event) {
            if let chars = nsEvent.characters, !chars.isEmpty {
                result += ", char='\(chars)'"
            }
            if let charsIgnoringMods = nsEvent.charactersIgnoringModifiers, !charsIgnoringMods.isEmpty {
                result += ", charIgnoringMods='\(charsIgnoringMods)'"
            }
        }
        
        return result
    }
}

