//
//  TypedWordBuffer.swift
//  Flipio
//
//  Created by Pavel Golub on 02/02/2026.
//

import AppKit
import ApplicationServices
import Carbon.HIToolbox
import os

/// Maintains a buffer of the "current word" the user is typing, per target process.
final class TypedWordBuffer {
    private var buffer: String = ""
    private var lastTargetPid: Int64 = -1
    
    func set(_ newBuffer: String) {
        buffer = newBuffer
    }
    
    func update(with event: CGEvent, type: CGEventType) {
        // Ignore synthetic events generated by Flipio itself
        if event.getIntegerValueField(.eventSourceUserData) == FlipioSyntheticEventUserData {
            return
        }
        
        // Track pid changes (keep pid as well)
        let targetPid = event.getIntegerValueField(.eventTargetUnixProcessID)
        if targetPid != lastTargetPid {
            reset(reason: "pid change (\(lastTargetPid) → \(targetPid))")
            lastTargetPid = targetPid
        }
        
        // Only process keyboard events
        guard type == .keyDown else {
            logEvent("non-keyDown event (type=\(type))", event: event, pid: targetPid)
            reset(reason: "non-keyDown event: \(type)")
            return
        }
        
        // Handle backspace/delete key
        let keyCode = event.getIntegerValueField(.keyboardEventKeycode)
        if keyCode == kVK_Delete {
            if !buffer.isEmpty {
                buffer.removeLast()
                FlipioApp.logger.debug(
                    "typedBuffer: backspace pressed, removed last char (buffer=\(self.getBuffer() ?? "nil"))"
                )
            } else {
                FlipioApp.logger.debug("typedBuffer: backspace pressed on empty buffer")
            }
            return
        }
        
        // Extract + validate text from event (nil => no valid text)
        guard let text = extractText(from: event) else {
            reset(reason: "no valid text")
            return
        }
        
        buffer.append(text)
        FlipioApp.logger.debug(
            "typedBuffer: updated (len=\(self.buffer.count) appended=\(text, privacy: .private(mask: .hash)) (buffer=\(self.getBuffer() ?? "nil"))"
        )
    }
    
    func reset(reason: String) {
        guard !buffer.isEmpty else { return }
        FlipioApp.logger.debug("typedBuffer: reset (\(reason, privacy: .public))")
        buffer = ""
    }
    
    func getBuffer() -> String? {
        return buffer
    }
    
    private func extractText(from event: CGEvent) -> String? {
        // Word-breaking keys reset the buffer even though some produce text
        let keyCode = Int(event.getIntegerValueField(.keyboardEventKeycode))
        let wordBreakingKeys: Set<Int> = [
            kVK_Return, kVK_Tab, kVK_Space, kVK_Escape,
            kVK_ForwardDelete,
            kVK_Home, kVK_End, kVK_PageUp, kVK_PageDown,
            kVK_LeftArrow, kVK_RightArrow, kVK_UpArrow, kVK_DownArrow,
        ]
        if wordBreakingKeys.contains(keyCode) {
            logEvent("word-breaking key", event: event)
            return nil
        }

        var length = 0
        var chars = [UniChar](repeating: 0, count: 32)
        event.keyboardGetUnicodeString(
            maxStringLength: chars.count,
            actualStringLength: &length,
            unicodeString: &chars
        )
        
        guard length > 0 else {
            logEvent("empty extracted text", event: event)
            return nil
        }
        
        return String(utf16CodeUnits: chars, count: length)
    }
    
    private func logEvent(_ message: String, event: CGEvent, pid: Int64? = nil) {
        let keyCode = event.getIntegerValueField(.keyboardEventKeycode)
        let flagsHex = String(event.flags.rawValue, radix: 16)
        FlipioApp.logger.debug(
            "typedBuffer: \(message, privacy: .public) (buffer=\(self.getBuffer() ?? "nil") pid=\(pid ?? -1) keyCode=\(keyCode) flags=0x\(flagsHex, privacy: .public))"
        )
    }
}
